[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "azt-logging"
version = "0.1.0"
description = "A lightweight logging handler for storing Python logs in Azure Table Storage."
authors = [
    { name = "runway28R" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"

keywords = [
    "logging",
    "azure",
    "azure-table-storage",
    "azure-data-tables",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: System :: Logging",
]

dependencies = [
    "azure-data-tables>=12.7.0"
]

[project.urls]
Homepage = "https://github.com/runway28R/azt-logging"
Source = "https://github.com/runway28R/azt-logging"
Issues = "https://github.com/runway28R/azt-logging/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["azt_logging*"]